### ISSUE TITLE
This sample is completely useless

### ISSUE THREAD

**Issue by Cloudmersive** [Azure-Samples/batch-dotnet-quickstart#7]
It does not show how to actually write code that runs on the remote batch servers - which is the whole / only point of batch!  For a sample to be useful I need:

- To see how does my C# code get onto the batch nodes
- How do I invoke it
- How do I coordinate between the nodes
- How do I fuse the output back together

This sample is a toy and has no value.  Please replace it with something actually useful.

**Comment by matthchr** [comment]
There are a number of other samples located [here](https://github.com/Azure-Samples/azure-batch-samples/tree/master/CSharp) - for example [TextSearch](https://github.com/Azure-Samples/azure-batch-samples/tree/master/CSharp/TextSearch) which do what you're asking.

This sample is intended as a getting started point for how to use Batch at a basic level - it is not intended to cover all possible use-cases.

**Comment by Cloudmersive** [comment]
But it doesn't cover ANY use cases!

**Comment by Cloudmersive** [comment]
It literally does not cover anything.  No one can use this.  It is a huge disservice for this to exist.
